(function(){
const URL='https://cjusebuzzyyaobsboccg.supabase.co';
const KEY='sb_publishable_mn-TVED7wp_FVKoKnCTUKQ_pC7dYcxO';
const db=supabase.createClient(URL,KEY);
const levels=['Não informado','0 — Nada','1 — Leve','2 — Moderada','3 — Forte','4 — Muito forte','5 — Extrema'];
const $=id=>document.getElementById(id);
function opts(){return '<option value="">Não informado</option>'+levels.slice(1).map((x,i)=>`<option value="${i}">${x}</option>`).join('')}
function style(){const s=document.createElement('style');s.textContent=`details,.notice,.status,pre{background:rgba(18,35,59,.9)!important;color:#f5f8ff!important;border-color:rgba(255,255,255,.1)!important}.muted{color:#b7c6d9!important}th,td{color:#eaf2ff!important;border-color:rgba(255,255,255,.08)!important}.chatbox{background:rgba(5,15,29,.72)!important;color:#f5f8ff!important}.msg.assistant{background:rgba(47,67,94,.9)!important;color:#f5f8ff!important}.enh-card{margin-top:18px!important;background:linear-gradient(145deg,rgba(53,224,255,.08),rgba(139,124,255,.1))!important}.level-guide{font-size:13px;color:#dcecff;margin:10px 0}.chart-switch{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.chart-switch button{color:#eaf2ff;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.1)}.chart-switch button.active{background:linear-gradient(135deg,rgba(53,224,255,.2),rgba(84,240,189,.18));border-color:rgba(84,240,189,.45)}.chart-title{font-weight:800;color:#dff9ff;margin:8px 0}`;document.head.appendChild(s)}
async function session(){const r=await db.auth.getSession();return r.data.session}
function setup(){style();
 const tab=[...document.querySelectorAll('.tabs button')].find(b=>b.dataset.t==='r');if(tab)tab.textContent='Registrar';
 const ft=[...document.querySelectorAll('.tabs button')].find(b=>b.dataset.t==='f');if(ft)ft.style.display='none';
 const fsec=$('f'),rsec=$('r'); if(fsec&&rsec){const form=$('fb');if(form){const card=document.createElement('div');card.className='card enh-card';card.innerHTML='<div class="eyebrow">Depois do treino</div><h3>Feedback da semana</h3><p class="muted">Registre como a semana está evoluindo. Esses dados podem ajudar o Treinador IA a ajustar o próximo treino quando houver fadiga, dor ou queda de recuperação.</p>';card.appendChild(form);rsec.appendChild(card)}fsec.style.display='none'}
 const run=$('runForm');if(run){
  const row=[...run.querySelectorAll('.row')].find(x=>x.querySelector('#calf'));if(row){$('calf').outerHTML='<select id="calf">'+opts()+'</select>';$('breath').outerHTML='<select id="breath">'+opts()+'</select>';const d=document.createElement('div');d.innerHTML='<div><label>Fadiga — nível percebido</label><select id="fatigue">'+opts()+'</select></div>';row.appendChild(d.firstElementChild);}
  run.addEventListener('submit',saveRun,true);
 }
 const oldEdit=window.editRun;if(oldEdit&&!oldEdit.__enh){const wrap=function(id){oldEdit(id);const x=window.__meu5kRuns?.find(r=>r.id===id);if(x&&$('fatigue'))$('fatigue').value=x.fatigue??''};wrap.__enh=true;window.editRun=wrap}
 addHistoryControls();
 refresh();
}
async function saveRun(e){e.preventDefault();e.stopImmediatePropagation();const s=await session();if(!s)return;const id=$('runId').value;const data={user_id:s.user.id,date:$('date').value,week:+$('week').value,session:$('ses').value,distance_km:$('dist').value?+$('dist').value:null,total_time_min:$('time').value?+$('time').value:null,continuous_min:$('cont').value?+$('cont').value:null,calf:$('calf').value===''?null:+$('calf').value,breathing:$('breath').value===''?null:+$('breath').value,fatigue:$('fatigue').value===''?null:+$('fatigue').value,recovery:$('rec').value,notes:$('notes').value||null};const q=id?await db.from('runs').update(data).eq('id',id):await db.from('runs').insert(data);if(q.error){alert(q.error.message);return}if(window.loadData)await window.loadData();if(window.clearRunForm)window.clearRunForm();alert(id?'Treino atualizado!':'Treino salvo!')}
function label(v){return v==null||v===''?'—':levels[+v]||v}
function addHistoryControls(){const h=$('h');if(!h||$('chartByRun'))return;const title=h.querySelector('h2');const p=document.createElement('p');p.className='muted';p.textContent='Compare sua evolução de duas formas: treino a treino ou consolidada por semana.';title.after(p);const sw=document.createElement('div');sw.className='chart-switch';sw.innerHTML='<button id="chartByRun" class="active" type="button">📈 Por treino</button><button id="chartByWeek" type="button">📊 Por semana</button><div class="chart-title" id="chartTitle">Distância por treino</div>';const ch=$('chart');ch.before(sw);$('chartByRun').onclick=()=>draw('run');$('chartByWeek').onclick=()=>draw('week')}
async function refresh(){const s=await session();if(!s)return;const q=await db.from('runs').select('*').eq('user_id',s.user.id).order('date',{ascending:true});if(q.error)return;window.__meu5kRuns=q.data||[];renderHistory(window.__meu5kRuns);draw('run')}
function renderHistory(rows){const hist=$('hist');if(!hist)return;hist.innerHTML=rows.slice().reverse().map(x=>`<tr><td>${x.date||''}</td><td>${x.week??''}</td><td>${x.session||''}</td><td>${x.distance_km??''}</td><td>${x.total_time_min??''}</td><td>${x.continuous_min??''}</td><td>${label(x.calf)}</td><td>${label(x.breathing)}</td><td>${label(x.fatigue)}</td><td>${x.recovery||''}</td><td>${x.notes||''}</td><td><button onclick="editRun('${x.id}')">Editar</button> <button class="danger" onclick="deleteRun('${x.id}')">Excluir</button></td></tr>`).join('')}
function draw(mode){const c=$('chart');if(!c)return;const rows=window.__meu5kRuns||[];const ctx=c.getContext('2d'),w=c.clientWidth||700,h=240,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);let vals=[];if(mode==='week'){const g={};rows.forEach(x=>g[x.week]=(g[x.week]||0)+(+x.distance_km||0));vals=Object.keys(g).sort((a,b)=>a-b).map(k=>({label:'S'+k,value:g[k]}));$('chartTitle').textContent='Distância por semana'}else{vals=rows.map((x,i)=>({label:'#'+(i+1),value:+x.distance_km||0}));$('chartTitle').textContent='Distância por treino'}if(!vals.length){ctx.fillStyle='#b7c6d9';ctx.fillText('Sem dados ainda',20,35);return}const max=Math.max(1,...vals.map(x=>x.value)),left=34,right=18,top=18,bottom=38;ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(left,h-bottom);ctx.lineTo(w-right,h-bottom);ctx.stroke();ctx.strokeStyle='#35e0ff';ctx.lineWidth=3;ctx.beginPath();vals.forEach((p,i)=>{const x=left+(w-left-right)*i/Math.max(1,vals.length-1),y=h-bottom-(h-top-bottom)*p.value/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
window.addEventListener('resize',()=>draw(window.__historyMode||'run'));window.__historyMode='run';
const oldRender=window.render;if(oldRender&&!oldRender.__enh){const wrap=function(){oldRender();refresh()};wrap.__enh=true;window.render=wrap}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(setup,200));else setTimeout(setup,200);
})();