(function(){
"use strict";
var $=function(id){return document.getElementById(id)};
var PT={settings:"Configurações",intro:"Controle sua conta, aparência, idioma e integrações em um só lugar.",profile:"👤 Perfil",sheets:"☁️ Google Sheets",custom:"🎨 Personalizar",account:"🔐 Conta",appearance:"Aparência",language:"Idioma",light:"Claro",dark:"Escuro",pt:"Português (Brasil)",en:"English",save:"Salvar alterações",photo:"Foto de perfil",choose:"Escolher foto",remove:"Remover foto",hint:"A foto fica salva neste dispositivo.",plan:"Visualização do plano",cards:"Cards",workout:"Por treino",week:"Por semana",feedback:"Feedback da semana"};
var EN={settings:"Settings",intro:"Manage your account, appearance, language and integrations in one place.",profile:"👤 Profile",sheets:"☁️ Google Sheets",custom:"🎨 Customize",account:"🔐 Account",appearance:"Appearance",language:"Language",light:"Light",dark:"Dark",pt:"Português (Brasil)",en:"English",save:"Save changes",photo:"Profile photo",choose:"Choose photo",remove:"Remove photo",hint:"The photo is saved on this device.",plan:"Plan view",cards:"Cards",workout:"By workout",week:"By week",feedback:"Weekly feedback"};
var tr=function(k){return (localStorage.meu5k_lang==="en"?EN:PT)[k]||PT[k]||k};
function css(){var s=document.createElement("style");s.textContent=".settings-panel{display:none}.settings-panel.active{display:block}.settings-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;margin:16px 0}.settings-card{padding:18px;border-radius:22px;background:linear-gradient(145deg,rgba(18,35,59,.9),rgba(8,20,36,.82));border:1px solid rgba(255,255,255,.1);box-shadow:0 14px 38px rgba(0,0,0,.16)}.settings-card h3{margin:0 0 7px}.settings-card p{margin:0 0 14px;color:#b7c6d9}.settings-card button{width:100%;margin-top:8px}.seg{display:flex;gap:8px;flex-wrap:wrap}.seg button{flex:1;min-width:110px}.profile-trigger{width:42px;height:42px;padding:0!important;border-radius:50%!important;overflow:hidden;background:rgba(255,255,255,.08)!important;display:inline-flex;align-items:center;justify-content:center;font-size:20px}.profile-trigger img{width:100%;height:100%;object-fit:cover}.hero-user{display:flex;align-items:center;gap:9px}.plan-view-switch{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.plan-view-switch button{background:rgba(255,255,255,.07)!important;color:#eaf2ff!important}.plan-view-switch button.active{background:linear-gradient(135deg,rgba(53,224,255,.2),rgba(84,240,189,.18))!important}.plan-list{display:grid;gap:10px}.plan-row{padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(20,40,66,.72)}.plan-meta{color:#b7c6d9;font-size:13px}.plan-main{margin-top:7px;color:#eaf2ff}.light-theme{--bg:#eef4fa!important;--text:#142235!important;--muted:#52657a!important}.light-theme body{}.light-theme .panel,.light-theme .card,.light-theme .settings-card,.light-theme .plan-row{background:rgba(255,255,255,.94)!important;color:#142235!important;border-color:rgba(20,34,53,.12)!important}.light-theme .muted{color:#52657a!important}.light-theme input,.light-theme select,.light-theme textarea{background:#fff!important;color:#142235!important;border-color:#cbd5e1!important}.light-theme .tabs{background:rgba(255,255,255,.88)!important}.light-theme .tabs button{color:#52657a!important}.light-theme th,.light-theme td{color:#142235!important}@media(max-width:700px){.settings-grid{grid-template-columns:1fr}}";document.head.appendChild(s)}
function theme(){return localStorage.meu5k_theme||"dark"}
function applyTheme(){document.documentElement.classList.toggle("light-theme",theme()==="light");document.body.classList.toggle("light-theme",theme()==="light")}
function avatar(){return localStorage.meu5k_avatar||""}
function updateAvatar(){var b=$("profileTrigger");if(!b)return;b.innerHTML=avatar()?"<img src='"+avatar()+"' alt='Perfil'>":"👤"}
function open(id){document.querySelectorAll(".panel").forEach(function(x){x.classList.remove("active")});var e=$(id);if(e)e.classList.add("active");document.querySelectorAll(".tabs button").forEach(function(b){b.classList.toggle("active",b.dataset.t===id)});window.scrollTo({top:0,behavior:"smooth"})}
function settings(){
 var app=$("app"),tabs=document.querySelector(".tabs");if(!app||!tabs||$("settings"))return;
 ["f","profile","g"].forEach(function(id){var b=document.querySelector('.tabs button[data-t="'+id+'"]');if(b)b.style.display="none"});
 var n=document.createElement("button");n.dataset.t="settings";n.textContent="⚙️ "+tr("settings");tabs.appendChild(n);n.onclick=function(){open("settings")};
 var sec=document.createElement("section");sec.id="settings";sec.className="panel card settings-panel";sec.innerHTML="<h2>"+tr("settings")+"</h2><p class='muted'>"+tr("intro")+"</p><div class='settings-grid'><div class='settings-card'><h3>"+tr("profile")+"</h3><p>Dados pessoais e personalização do treinamento.</p><button id='openProfile' class='primary'>Abrir perfil</button></div><div class='settings-card'><h3>"+tr("sheets")+"</h3><p>Sincronize seus dados com sua própria planilha.</p><button id='openSheets'>Configurar Google Sheets</button></div><div class='settings-card'><h3>"+tr("custom")+"</h3><p>"+tr("appearance")+" e "+tr("language")+".</p><button id='openCustom'>Personalizar aplicativo</button></div><div class='settings-card'><h3>"+tr("account")+"</h3><p>Gerencie e-mail e senha.</p><button id='openAccount'>Conta e segurança</button></div></div><div id='settingsSub'></div>";
 app.insertBefore(sec,app.querySelector(".panel"));
 $("openProfile").onclick=function(){sub("profile")};$("openSheets").onclick=function(){sub("g")};$("openCustom").onclick=function(){sub("custom")};$("openAccount").onclick=function(){sub("account")};
}
function sub(id){
 var box=$("settingsSub");box.innerHTML="";
 if(id==="profile"){var p=$("profile");p.classList.add("active");box.appendChild(p);return}
 if(id==="g"){var g=$("g");g.classList.add("active");box.appendChild(g);return}
 if(id==="custom"){box.innerHTML="<div class='settings-card'><h3>"+tr("custom")+"</h3><label>"+tr("appearance")+"</label><div class='seg'><button id='dark'>🌙 "+tr("dark")+"</button><button id='light'>☀️ "+tr("light")+"</button></div><label>"+tr("language")+"</label><div class='seg'><button id='pt'>🇧🇷 "+tr("pt")+"</button><button id='en'>🇺🇸 "+tr("en")+"</button></div><hr><label>"+tr("photo")+"</label><div class='seg'><button id='choose'>📷 "+tr("choose")+"</button><button id='remove'>✕ "+tr("remove")+"</button></div><input id='photoFile' type='file' accept='image/*' class='hidden'><p class='muted'>"+tr("hint")+"</p></div>";$("dark").onclick=function(){localStorage.meu5k_theme="dark";applyTheme()};$("light").onclick=function(){localStorage.meu5k_theme="light";applyTheme()};$("pt").onclick=function(){localStorage.meu5k_lang="pt";location.reload()};$("en").onclick=function(){localStorage.meu5k_lang="en";location.reload()};$("choose").onclick=function(){$("photoFile").click()};$("remove").onclick=function(){localStorage.removeItem("meu5k_avatar");updateAvatar()};$("photoFile").onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){localStorage.meu5k_avatar=r.result;updateAvatar()};r.readAsDataURL(f)};return}
 if(id==="account"){box.innerHTML="<div class='settings-card'><h3>"+tr("account")+"</h3><label>E-mail</label><input id='accEmail' type='email'><label>Nova senha</label><input id='accPass' type='password' minlength='6'><button id='saveAcc' class='primary'>"+tr("save")+"</button><div id='accStatus' class='status hidden'></div></div>";$("accEmail").value=user&&user.email||"";$("saveAcc").onclick=async function(){var st=$("accStatus");st.classList.remove("hidden");try{var em=$("accEmail").value.trim(),pw=$("accPass").value;if(em&&user&&em!==user.email){var a=await sb.auth.updateUser({email:em});if(a.error)throw a.error}if(pw){var b=await sb.auth.updateUser({password:pw});if(b.error)throw b.error}st.textContent="Conta atualizada."}catch(e){st.textContent=e.message||"Não foi possível atualizar."}}}
}
function hero(){
 var top=document.querySelector(".hero>div");if(!top)return;var ue=$("userEmail");if(ue)ue.style.display="none";var host=top.lastElementChild;host.classList.add("hero-user");var name=$("heroName");if(!name){name=document.createElement("span");name.id="heroName";host.insertBefore(name,host.firstChild)}name.textContent=profile&&profile.display_name?profile.display_name:"Corredor";var b=$("profileTrigger");if(!b){b=document.createElement("button");b.id="profileTrigger";b.className="profile-trigger";b.title=tr("profile");host.insertBefore(b,host.firstChild);b.onclick=function(){open("settings");sub("custom")}}updateAvatar()}
function noGuide(){document.querySelectorAll(".level-guide").forEach(function(x){x.remove()})}
function charts(){
 var c=$("chart");if(!c)return;if($("histSwitch"))return;var sw=document.createElement("div");sw.id="histSwitch";sw.className="plan-view-switch";sw.innerHTML="<button id='histRun' class='active'>📈 "+tr("workout")+"</button><button id='histWeek'>📊 "+tr("week")+"</button>";c.before(sw);var title=document.createElement("div");title.id="histTitle";title.className="chart-title";c.before(title);$("histRun").onclick=function(){drawHist("run")};$("histWeek").onclick=function(){drawHist("week")};drawHist("run")}
function drawHist(mode){
 var c=$("chart");if(!c)return;var rows=window.__meu5kRuns||runs||[],ctx=c.getContext("2d"),W=c.clientWidth||760,H=270,d=devicePixelRatio||1;c.width=W*d;c.height=H*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,W,H);var vals=[];
 if(mode==="week"){var g={};rows.forEach(function(x){g[x.week]=(g[x.week]||0)+(+x.distance_km||0)});Object.keys(g).sort(function(a,b){return +a-+b}).forEach(function(k){vals.push({label:"S"+k,value:+g[k].toFixed(2)})})}else rows.forEach(function(x,i){vals.push({label:String(i+1),value:+(+x.distance_km||0).toFixed(2)})});
 $("histTitle").textContent=(mode==="week"?tr("week")+" — Distância":" "+tr("workout")+" — Distância")+" (km)";if(!vals.length){ctx.fillStyle="#91a4bd";ctx.fillText("Sem dados ainda",20,35);return}
 var max=Math.max(1,...vals.map(function(x){return x.value})),L=52,R=22,T=28,B=48;ctx.font="12px system-ui";ctx.strokeStyle="rgba(145,164,189,.22)";ctx.fillStyle="#b7c6d9";
 for(var i=0;i<=4;i++){var v=max*i/4,y=H-B-(H-T-B)*i/4;ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(W-R,y);ctx.stroke();ctx.fillText(v.toFixed(1)+" km",5,y+4)}
 ctx.strokeStyle="#35e0ff";ctx.lineWidth=3;ctx.beginPath();vals.forEach(function(p,i){var x=vals.length===1?(W+L)/2:L+(W-L-R)*i/(vals.length-1),y=H-B-(H-T-B)*p.value/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();vals.forEach(function(p,i){var x=vals.length===1?(W+L)/2:L+(W-L-R)*i/(vals.length-1),y=H-B-(H-T-B)*p.value/max;ctx.fillStyle="#54f0bd";ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill();ctx.fillStyle="#f5f8ff";ctx.textAlign="center";ctx.fillText(p.value.toFixed(2)+" km",x,Math.max(14,y-10));if(vals.length<=14)ctx.fillText(p.label,x,H-20)})}
function planViews(){
 var anchor=$("planSummary");if(!anchor||$("planViews"))return;var sw=document.createElement("div");sw.id="planViews";sw.className="plan-view-switch";sw.innerHTML="<b style='width:100%;color:#b7c6d9'>"+tr("plan")+"</b><button id='pvCards' class='active'>▦ "+tr("cards")+"</button><button id='pvWorkout'>☷ "+tr("workout")+"</button><button id='pvWeek'>▤ "+tr("week")+"</button>";anchor.after(sw);$("pvCards").onclick=function(){renderPV("cards")};$("pvWorkout").onclick=function(){renderPV("workout")};$("pvWeek").onclick=function(){renderPV("week")};window.__pvMode="cards";window.__pvRender=function(){renderPV(window.__pvMode||"cards")}}
function renderPV(mode){
 if(!currentPlan||!currentPlan.sessions)return;window.__pvMode=mode;["pvCards","pvWorkout","pvWeek"].forEach(function(x){$(x)&&$(x).classList.remove("active")});$("pv"+(mode==="cards"?"Cards":mode==="workout"?"Workout":"Week"))?.classList.add("active");var box=$("weeks"),ss=currentPlan.sessions;
 if(mode==="cards"){if(window.__basePlanRender)window.__basePlanRender();return}
 if(mode==="workout"){box.innerHTML="<div class='plan-list'>"+ss.map(function(s){return "<div class='plan-row'><b>"+s.title+"</b><div class='plan-meta'>Semana "+s.week+" · "+(s.scheduled_day||"Dia")+" · "+s.session_type+" · "+(s.target_duration_min||"")+" min</div><div class='plan-main'>"+(s.main_set||"")+"</div></div>"}).join("")+"</div>";return}
 var g={};ss.forEach(function(s){(g[s.week]??=[]).push(s)});box.innerHTML="<div class='plan-list'>"+Object.keys(g).map(function(w){return "<div class='plan-row'><b>Semana "+w+"</b><div class='plan-meta'>"+g[w].length+" treino(s)</div>"+g[w].map(function(s){return "<div style='margin-top:12px;padding-top:12px;border-top:1px solid rgba(255,255,255,.08)'><b>"+s.title+"</b><div class='plan-meta'>"+(s.scheduled_day||"Dia")+" · "+s.session_type+" · "+(s.target_duration_min||"")+" min</div><div class='plan-main'>"+(s.main_set||"")+"</div></div>"}).join("")+"</div>"}).join("")+"</div>"}
function install(){
 css();applyTheme();noGuide();var tab=document.querySelector('.tabs button[data-t="r"]');if(tab)tab.textContent="Registrar";var oldF=document.querySelector('.tabs button[data-t="f"]');if(oldF)oldF.style.display="none";
 var h=$("f")?.querySelector("h2");if(h)h.textContent=tr("feedback");var labels=document.querySelectorAll("label");labels.forEach(function(l){if(l.textContent.indexOf("Panturrilha")>=0)l.textContent="Panturrilha 0–5";if(l.textContent.indexOf("Respiração")>=0)l.textContent="Respiração 0–5"});
 settings();hero();charts();planViews();
 var base=window.renderPlan;if(base&&!base.__v2){window.__basePlanRender=base;var wrap=function(){base();if(window.__pvMode!=="cards")setTimeout(function(){renderPV(window.__pvMode)},0)};wrap.__v2=true;window.renderPlan=wrap}
 var r=window.render;if(r&&!r.__v2){var wr=function(){r();hero();noGuide();drawHist("run");if(window.__pvMode!=="cards")setTimeout(function(){renderPV(window.__pvMode)},0)};wr.__v2=true;window.render=wr}
 var run=$("runForm");if(run){var f=$("fatigue");if(f)f.setAttribute("aria-label","Fadiga 0–5");}
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(install,450)});else setTimeout(install,450);
window.addEventListener("resize",function(){if($("histSwitch"))drawHist("run")});
})();